### ISSUE TITLE
How to get user details after login?

### ISSUE THREAD

**Issue by edent** [auth0/symfony#153]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I've followed the tutorial at https://github.com/auth0/symfony and I can successfully authenticate with Auth0... on *one* page.

When I try `$this->getUser()` on any other page, I don't receive the user's details.

At the moment, as per the tutorial, the route `/private` is in the firewall. When I access it, i get the Auth0 login prompt. After a successful login, I see the user's name, nickname, etc. Once the user is logged in, how do I get their details on pages which aren't in the firewall?

I'm not sure if this is me not understanding Symfony's firewall or Auth0's model - but I would be grateful for some pointers.

### Reproduction

1. Follow the instructions in the repo
2. Authenticate against `/private`
3. Try to get the user details on a different page.

### Additional context

I was asked to add this via https://community.auth0.com/t/symfony-how-to-get-user-details-after-login/106332/1

### jwt-auth-bundle version

I used composer as per the instructions

### Symfony version

6.3

### PHP version

8.1.2

**Comment by evansims** [comment]
Hi @adent,

Symfony only invokes guard logic (and therefore establishes user authentication state) on requests that are routed through the guard, as defined by the firewall. If you are trying to access user information on routes that aren't served through the guard, the authentication state won't reflect anything.

As an alternative, you can access the SDK service directly. Symfony is built around auto-wiring, allowing you to retrieve any service instance within your application by defining what you need in your constructors. The SDK is accessible through the same means.

Presumably, this is about using the `authenticator` rather than the `authorizer,` yes? If so, here's an example of that:

```php
<?php

namespace Auth0\Symfony\Controllers;

use Auth0\Symfony\Service as Auth0Service;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\{Request, Response};

final class AuthenticationController extends AbstractController
{
    public function __construct(
        private Auth0Service $auth0,
    )
    {
    }

	public function login(
		Request $request
	): Response {
		$sdk = $this->auth0->getSdk();

		var_dump($sdk->getCredentials());
	}
}
```

This queries the underlying PHP SDK directly. The `getCredentials()` method returns an object, which includes user profile information, ID and Access tokens, and so forth. You can learn more about [using the PHP SDK here](https://github.com/auth0/auth0-PHP).

**Comment by edent** [comment]
All I get when I try that is 

`Invalid service "Auth0\Symfony\Controllers\AuthenticationController": method "__construct()" has no argument named "$authenticator". Check your service definition.`

I'm sorry if I'm asking something obvious here. It's just frustrating that the documentation stops at the simplest use-case.

**Comment by alebedev80** [comment]
@evansims but there is not Auth0 service in autowiring:

```
bin/console debug:autowiring | grep uth0 
 Psr\Cache\CacheItemPoolInterface $auth0ManagementTokenCache (auth0_management_token_cache)
 Psr\Cache\CacheItemPoolInterface $auth0TokenCache (auth0_token_cache)
 Symfony\Contracts\Cache\CacheInterface $auth0ManagementTokenCache (auth0_management_token_cache)
 Symfony\Contracts\Cache\CacheInterface $auth0TokenCache (auth0_token_cache)
 Symfony\Contracts\Cache\TagAwareCacheInterface $auth0ManagementTokenCache (.auth0_management_token_cache.taggable)
 Symfony\Contracts\Cache\TagAwareCacheInterface $auth0TokenCache (.auth0_token_cache.taggable)
 ```
